### ISSUE TITLE
Can't create the Model NodeSet2. 

### ISSUE THREAD

**Issue by s97606183** [Pro/opcua-animal-cs#2]
I try to do this example,
but run the build_model.bat,
The folder animal/UA_Test/opcua-animal-cs/animalModel is empty.
I have create the Model.xml.

I use the windows to build the model.

Thank you very much.

**Comment by Pro** [comment]
What were the exact steps you performed?

It should work with:

```
git clone https://github.com/Pro/opcua-animal-cs
cd opcua-animal-cs
git submodule update --init --recursive
cd model_compiler
nuget.exe install -OutputDirectory packages ModelCompiler/packages.config
msbuild "ModelCompiler Solution.sln" /p:TargetFrameworkVersion="v4.5"
cd ..
build_model.bat
```

If not, please show the full output of the command here.


`animal/UA_Test/opcua-animal-cs/animalModel` is not referring to a folder, but to this file:
https://github.com/Pro/opcua-animal-cs/blob/master/animalModel.xml

**Comment by s97606183** [comment]
My problem is solved.
Thanks for your reply.

I'm learning to create OPC UA Information Models,
and try to use the compiler to convert the AML file to NodeSet2.xml Format.

Thank you very much again.
